version: '3.4'

services:
  authapp:
    image: ${DOCKER_REGISTRY-}authapp
    build:
      context: .
      dockerfile: AuthApp/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest 
